version: '2'

networks:
  net:
    driver: bridge

services:

  data1:
    image: mongo:3.4
    container_name: data1
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  data2:
    image: mongo:3.4
    container_name: data2
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  data3:
    image: mongo:3.4
    container_name: data3
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  cfg1:
    image: mongo:3.4
    container_name: cfg1
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  cfg2:
    image: mongo:3.4
    container_name: cfg2
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  cfg3:
    image: mongo:3.4
    container_name: cfg3
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  mongos1:
    image: mongo:3.4
    container_name: mongos1
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017
    expose:
      - 27017
    networks:
      - net

  mongos2:
    image: mongo:3.4
    container_name: mongos2
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017
    expose:
      - 27017
    networks:
      - net

  bootstrap:
    image: stefanprodan/mongo-bootstrap:latest
    container_name: mongo-bootstrap
    command:
      - '-dataSet=datars/data1:27017,data2:27017,data3:27017'
      - '-configSet=cfgrs/cfg1:27017,cfg2:27017,cfg3:27017'
      - '-mongos=mongos1:27017,mongos2:27017'
    networks:
      - net
